// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0EVp9P26s-JTCVARInILaSSzBDKigjiY',
    appId: '1:252653590543:web:39a36117fe9d5a2fd0eb7a',
    messagingSenderId: '252653590543',
    projectId: 'e-commerce-app-9304e',
    authDomain: 'e-commerce-app-9304e.firebaseapp.com',
    storageBucket: 'e-commerce-app-9304e.firebasestorage.app',
    measurementId: 'G-H6B1PJE6WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk5B1xlj3h48vyCXQE0VbbubZI8CqFx-o',
    appId: '1:252653590543:android:c1f5cb03f4dd19a5d0eb7a',
    messagingSenderId: '252653590543',
    projectId: 'e-commerce-app-9304e',
    storageBucket: 'e-commerce-app-9304e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFQjCRC58Uvr2yfmY2q3WoHogLy8bOFwg',
    appId: '1:252653590543:ios:24b947882118022cd0eb7a',
    messagingSenderId: '252653590543',
    projectId: 'e-commerce-app-9304e',
    storageBucket: 'e-commerce-app-9304e.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFQjCRC58Uvr2yfmY2q3WoHogLy8bOFwg',
    appId: '1:252653590543:ios:24b947882118022cd0eb7a',
    messagingSenderId: '252653590543',
    projectId: 'e-commerce-app-9304e',
    storageBucket: 'e-commerce-app-9304e.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0EVp9P26s-JTCVARInILaSSzBDKigjiY',
    appId: '1:252653590543:web:d9b06ac53d9ba25fd0eb7a',
    messagingSenderId: '252653590543',
    projectId: 'e-commerce-app-9304e',
    authDomain: 'e-commerce-app-9304e.firebaseapp.com',
    storageBucket: 'e-commerce-app-9304e.firebasestorage.app',
    measurementId: 'G-ZKPN09ZHXX',
  );
}
